---
version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - USER=beellz
      - PASS=32502310
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/beellz/trans-movie/config:/config
      - /home/beellz/trans-movie/download:/downloads
      - /home/beellz/trans-movie/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped